export const languages = {
  en: {
    name: "English",
    flag: "🇺🇸",
    translations: {
      home: "Home",
      services: "Services",
      messages: "Messages",
      listings: "Listings",
      profile: "Profile",
      analytics: "Analytics",
      searchProperties: "Search properties or locations...",
      filters: "Filters",
      sortBy: "Sort By",
      propertyType: "Property Type",
      all: "All",
      forSale: "For Sale",
      forRent: "For Rent",
      newest: "Newest First",
      priceLow: "Price: Low to High",
      priceHigh: "Price: High to Low",
      popular: "Most Popular",
      bedrooms: "Bedrooms",
      bathrooms: "Bathrooms",
      priceRange: "Price Range",
      viewDetails: "View Details",
      contactSeller: "Contact Seller",
      addToFavorites: "Add to Favorites",
      removeFromFavorites: "Remove from Favorites",
      myListings: "My Listings",
      addListing: "Add Listing",
      balance: "Balance",
      mining: "Mining",
      startMining: "Start Mining",
      claimRewards: "Claim Rewards",
      privacyPolicy: "Privacy Policy",
      termsOfService: "Terms of Service",
      aboutUs: "About Us",
      language: "Language",
      selectLanguage: "Select Language",
    }
  },
  es: {
    name: "Español",
    flag: "🇪🇸",
    translations: {
      home: "Inicio",
      services: "Servicios",
      messages: "Mensajes",
      listings: "Listados",
      profile: "Perfil",
      analytics: "Analítica",
      searchProperties: "Buscar propiedades o ubicaciones...",
      filters: "Filtros",
      sortBy: "Ordenar por",
      propertyType: "Tipo de Propiedad",
      all: "Todos",
      forSale: "En Venta",
      forRent: "En Alquiler",
      newest: "Más Reciente",
      priceLow: "Precio: Bajo a Alto",
      priceHigh: "Precio: Alto a Bajo",
      popular: "Más Popular",
      bedrooms: "Dormitorios",
      bathrooms: "Baños",
      priceRange: "Rango de Precio",
      viewDetails: "Ver Detalles",
      contactSeller: "Contactar Vendedor",
      addToFavorites: "Agregar a Favoritos",
      removeFromFavorites: "Quitar de Favoritos",
      myListings: "Mis Listados",
      addListing: "Agregar Listado",
      balance: "Saldo",
      mining: "Minería",
      startMining: "Iniciar Minería",
      claimRewards: "Reclamar Recompensas",
      privacyPolicy: "Política de Privacidad",
      termsOfService: "Términos de Servicio",
      aboutUs: "Sobre Nosotros",
      language: "Idioma",
      selectLanguage: "Seleccionar Idioma",
    }
  },
  fr: {
    name: "Français",
    flag: "🇫🇷",
    translations: {
      home: "Accueil",
      services: "Services",
      messages: "Messages",
      listings: "Annonces",
      profile: "Profil",
      analytics: "Analytique",
      searchProperties: "Rechercher des propriétés ou des emplacements...",
      filters: "Filtres",
      sortBy: "Trier par",
      propertyType: "Type de Propriété",
      all: "Tous",
      forSale: "À Vendre",
      forRent: "À Louer",
      newest: "Plus Récent",
      priceLow: "Prix: Bas à Haut",
      priceHigh: "Prix: Haut à Bas",
      popular: "Plus Populaire",
      bedrooms: "Chambres",
      bathrooms: "Salles de Bain",
      priceRange: "Fourchette de Prix",
      viewDetails: "Voir les Détails",
      contactSeller: "Contacter le Vendeur",
      addToFavorites: "Ajouter aux Favoris",
      removeFromFavorites: "Retirer des Favoris",
      myListings: "Mes Annonces",
      addListing: "Ajouter une Annonce",
      balance: "Solde",
      mining: "Minage",
      startMining: "Commencer le Minage",
      claimRewards: "Réclamer les Récompenses",
      privacyPolicy: "Politique de Confidentialité",
      termsOfService: "Conditions d'Utilisation",
      aboutUs: "À Propos",
      language: "Langue",
      selectLanguage: "Sélectionner la Langue",
    }
  },
  zh: {
    name: "中文",
    flag: "🇨🇳",
    translations: {
      home: "首页",
      services: "服务",
      messages: "消息",
      listings: "列表",
      profile: "个人资料",
      analytics: "分析",
      searchProperties: "搜索房产或位置...",
      filters: "筛选",
      sortBy: "排序方式",
      propertyType: "房产类型",
      all: "全部",
      forSale: "出售",
      forRent: "出租",
      newest: "最新",
      priceLow: "价格：低到高",
      priceHigh: "价格：高到低",
      popular: "最受欢迎",
      bedrooms: "卧室",
      bathrooms: "浴室",
      priceRange: "价格范围",
      viewDetails: "查看详情",
      contactSeller: "联系卖家",
      addToFavorites: "添加到收藏",
      removeFromFavorites: "从收藏中移除",
      myListings: "我的列表",
      addListing: "添加列表",
      balance: "余额",
      mining: "挖矿",
      startMining: "开始挖矿",
      claimRewards: "领取奖励",
      privacyPolicy: "隐私政策",
      termsOfService: "服务条款",
      aboutUs: "关于我们",
      language: "语言",
      selectLanguage: "选择语言",
    }
  },
  pt: {
    name: "Português",
    flag: "🇧🇷",
    translations: {
      home: "Início",
      services: "Serviços",
      messages: "Mensagens",
      listings: "Listagens",
      profile: "Perfil",
      analytics: "Análises",
      searchProperties: "Pesquisar propriedades ou locais...",
      filters: "Filtros",
      sortBy: "Ordenar por",
      propertyType: "Tipo de Propriedade",
      all: "Todos",
      forSale: "À Venda",
      forRent: "Para Alugar",
      newest: "Mais Recente",
      priceLow: "Preço: Baixo a Alto",
      priceHigh: "Preço: Alto a Baixo",
      popular: "Mais Popular",
      bedrooms: "Quartos",
      bathrooms: "Banheiros",
      priceRange: "Faixa de Preço",
      viewDetails: "Ver Detalhes",
      contactSeller: "Contatar Vendedor",
      addToFavorites: "Adicionar aos Favoritos",
      removeFromFavorites: "Remover dos Favoritos",
      myListings: "Minhas Listagens",
      addListing: "Adicionar Listagem",
      balance: "Saldo",
      mining: "Mineração",
      startMining: "Iniciar Mineração",
      claimRewards: "Reivindicar Recompensas",
      privacyPolicy: "Política de Privacidade",
      termsOfService: "Termos de Serviço",
      aboutUs: "Sobre Nós",
      language: "Idioma",
      selectLanguage: "Selecionar Idioma",
    }
  }
};

export type LanguageCode = keyof typeof languages;

export function getTranslation(lang: LanguageCode, key: keyof typeof languages.en.translations): string {
  return languages[lang]?.translations[key] || languages.en.translations[key];
}
